version: '3.9'
services:
  client:
    build: ./client
    ports:
      - "5173:3000"
    restart: always

  server:
    build: ./server
    ports:
      - "5433:5432"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short_links
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433"

volumes:
  pgdata:
